@baseUrl = {{host}}:{{port}}/api/{{version}}
@contentType = application/json

###

@endpoint = bank-account
@id = 1
@employee = 1

### BankAccount create
POST http://{{baseUrl}}/{{endpoint}}
Content-Type: {{contentType}}

{
    "bank": "Brasil",
    "agency": "5846",
    "account": "5565655",
    "account_type": "corrente",
    "employee": {{employee}}
}


### BankAccount get by id /bank-account/<id: int>
GET http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}


### BankAccount get all - return a list of BankAccount with all BankACcounts active
GET http://{{baseUrl}}/{{endpoint}}
Content-Type: {{contentType}}


### BankAccount update - return BankAccount updated
PUT http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}

{
    "bank": "Brasil",
    "agency": "5846",
    "account": "5565655",
    "account_type": "corrente",
    "employee": {{employee}}
}

## BankAccount delete by id - return id, is_active and deleted_at
DELETE http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}/
