@baseUrl = {{host}}:{{port}}/api/{{version}}
@contentType = application/json

###

@endpoint = employee
@id = 1
@function = 1

### Employee create - return created user
POST http://{{baseUrl}}/{{endpoint}}
Content-Type: {{contentType}}

{
    "full_name": "John Doe",
    "tax_id": "111.222.333-00",
    "national_id": "187876MG",
    "date_of_birth": "01/02/2000",
    "issuing_body": "Secretaria de Segurança Pública (SSP) ",
    "gender": "M",
    "martial_status": "CASADO",
    "registration": "1111",
    "supervisor": false,
    "manager": false,
    "salary": 8000.00,
    "contract_date": "01/02/1990",
    "function": "{{function}}",
    "address": {
        "street": "Rua Nome",
        "number": "999",
        "neighborhood": "Centro",
        "city": "Rio de Janeiro",
        "zip_code": "48625815",
        "state": "Rio de Janeiro",
    },
    "contact": {
        "phone_number": "64996521512",
        "email": "johndoe@domain.com"
    },
    "bank_account": {
        "bank": "Brasil",
        "agency": "5846",
        "account": "5565655",
        "account_type": "corrente"
    },
    "clothing": {
        "shirt_size": "m",
        "pants_size": "m",
        "shoe_size": "40"
    }
}


### Employee get by id /employee/<id: int>
GET http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}


### Employee get all - return a list of employee with all employees active
GET http://{{baseUrl}}/{{endpoint}}
Content-Type: {{contentType}}

### Employee update - return employee updated
PUT http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}

{
    "id": "{{id}}",
    "full_name": "John Doe",
    "tax_id": "111.222.333-00",
    "national_id": "187876MG",
    "date_of_birth": "01/02/2000",
    "issuing_body": "Secretaria de Segurança Pública (SSP)",
    "gender": "M",
    "martial_status": "CASADO",
    "registration": "1111",
    "supervisor": false,
    "manager": false,
    "salary": 8000.00,
    "contract_date": "01/02/1990",
    "function": 3,
    "address": {
        "street": "Rua Nome",
        "number": "999",
        "neighborhood": "Centro",
        "city": "Rio de Janeiro",
        "zip_code": "48625815",
        "state": "Rio de Janeiro",
    },
    "contact": {
        "phone_number": "64996521512",
        "email": "johndoe@domain.com"
    },
    "bank_account": {
        "bank": "Brasil",
        "agency": "5846",
        "account": "5565655",
        "account_type": "corrente"
    },
    "clothing": {
        "shirt_size": "m",
        "pants_size": "m",
        "shoe_size": "40"
    }
}


## Employee delete by id - return id, is_active and deleted_at
DELETE http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}
