@baseUrl = {{host}}:{{port}}/api/{{version}}
@contentType = application/json

###

@endpoint = function
# @id = 1


### Function create

# @name createFunction
POST http://{{baseUrl}}/{{endpoint}} HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Motorista",
    "description": "Motorista de carro de passeio"
}


### Function get by id /function/<id: int>

@id = {{createFunction.response.body.$.id}}

GET http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}


### Function get all - return a list of Function
GET http://{{baseUrl}}/{{endpoint}}
Content-Type: {{contentType}}


### Function update - return Function updated

PUT http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}

{
    "name": "Motorista Trator",
    "description": "Motorista de trator"
}


## Function delete by id - return id, is_active and deleted_at
DELETE http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}
