@baseUrl = {{host}}:{{port}}
@contentType = application/json

@endpoint = user


# name=foo&password=bar

###

# @name createUser
POST http://{{baseUrl}}/user/
Content-Type: application/json

{
    "name": "Name Test",
    "email": "john.doe@email.com",
    "password": "passwd@123"
}


### User get by id /user/<id: int>

@id = {{createUser.request.body.$.id}}
GET http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}


### User get all - return a list of User

GET http://{{baseUrl}}/{{endpoint}}
Content-Type: {{contentType}}


### User update - return User updated

PUT http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}

{
    "email": "john.updated.john@email.com",
    "password_hash": "321@passwd"
}


### User delete by id - return id, is_active and deleted_at

DELETE http://{{baseUrl}}/{{endpoint}}/{{id}}
Content-Type: {{contentType}}


 441, in load
teca_api  |     self.loaded_app = self.loaded_app()
